# -- Web site root --
# The web container uses /var/www/html as site root. Make sure the html  dir is
# available or has is symlinked correctly.
#
# 'password' => getenv('MYSQL_ENV_MYSQL_ROOT_PASSWORD'),
# 'host'     => getenv('MYSQL_PORT_3306_TCP_ADDR'),

data:
  image: ubuntu:14.04
  volumes:
    - /var/logs
    - src:/var/www
#db:
#  build: ./mysql
#  environment:
#    - MYSQL_ROOT_PASSWORD=root
#  volumes_from:
#    - data
web:
  build: ./php
  ports:
    - 80
  volumes_from:
    - data
